AWSTemplateFormatVersion: '2010-09-09'
Description: >
  cloudblocks relational database

Parameters:
  # Project's name
  ProjectName:
    Type: String
    Description: The name of the project. Used to tag resources.
    Default: cloudblocks
  # Deployment environment
  Environment:
    Type: String
    Description: The environment name. Used to tag resources.
    Default: dev

Resources:
  Database:
    Type: AWS::RDS::DBInstance
    Properties:
      DBName: !Sub "${ProjectName}-db-${Environment}"
      AllocatedStorage: 20
      DBInstanceClass: db.t3.micro
      Engine: mysql
      MasterUsername: "{{resolve:ssm:/cloudblocks/db/master-username:1}}"
      MasterUserPassword: "{{resolve:ssm-secure:/cloudblocks/db/master-password:1}}" 
      
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: API Gateway endpoint URL for Prod stage for Hello World 
      function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/Prod/hello/"
  HelloWorldFunction:
    Description: Hello World Lambda Function ARN
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: Implicit IAM Role created for Hello World function
    Value: !GetAtt HelloWorldFunctionRole.Arn
