AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  cloudblocks serverless DynamoDB database

Parameters:
  # Project's name
  ProjectName:
    Type: String
    Description: The name of the project. Used to tag resources.
    Default: cloudblocks
  # Deployment environment
  Environment:
    Type: String
    Description: The environment name. Used to tag resources.
    Default: dev

Resources:
# Project Table
  CloudblocksTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${ProjectName}-single-table-${Environment}"
      TableClass: STANDARD
      BillingMode: PROVISIONED
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      Tags:
        - Key: project
          Value: !Ref ProjectName


Outputs:
  CloudblocksDynamo:
    Description: Cloudblocks DynamoDB table ID
    Value: !Ref CloudblocksTable
    Export:
      Name: CloudblocksTable

      
