AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  cloudblocks-api

  SAM Template for the cloudblocks API project. 

Globals:
  Function:
    Timeout: 15
    # You can add LoggingConfig parameters such as the Logformat, Log Group, and SystemLogLevel or ApplicationLogLevel. Learn more here https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-loggingconfig.
    LoggingConfig:
      LogFormat: JSON

Parameters:
  # Project's name
  ProjectName:
    Type: String
    Description: The name of the project. Used to tag resources.
    Default: cloudblocks
  # Deployment environment
  Environment:
    Type: String
    Description: The environment name. Used to tag resources.
    Default: dev

Resources:
  # S3
  # S3 bucket policy to allow Cloublock's CF distro to access the content bucket.
  ContentBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref ContentBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowCloudFrontContentDistro
            Effect: Allow
            Principal:
              Service: "cloudfront.amazonaws.com"
            Action: "s3:GetObject"
            Resource: !Sub "${ContentBucket.Arn}/*"
            Condition:
              StringEquals:
                AWS:SourceArn: !Sub "arn:aws:cloudfront::${AWS::AccountId}:distribution/${ContentDistribution}"
        
  # Bucket to store the courses' video content. The bucket must be private and versioned to enable recovery.
  # Access to content will be granted through signed URLs generated by the API.
  ContentBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${ProjectName}-content-bucket-${Environment}"
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: project
          Value: !Ref ProjectName

  # CDN
  # CDN to access the content bucket.
  ContentDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        DefaultCacheBehavior:
          ViewerProtocolPolicy: redirect-to-https
          TargetOriginId: ContentBucketOrigin
          CachePolicyId: !Ref DefaultCachePolicy
          AllowedMethods:
            - GET
            - HEAD
          CachedMethods: 
            - GET
            - HEAD
        Origins:
          - Id: ContentBucketOrigin
            DomainName: !GetAtt ContentBucket.DomainName
            OriginAccessControlId: !Ref ContentOAC
            S3OriginConfig:
              OriginReadTimeout: 10
              OriginAccessIdentity: ""
      Tags:
        - Key: project
          Value: !Ref ProjectName

  # OAC to grant S3 access to the Distro
  ContentOAC:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: !Sub "${ProjectName}-content-oac"
        Description: OAC to grant S3 access to CDN distros
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  DefaultCachePolicy:
    Type: AWS::CloudFront::CachePolicy
    Properties:
      CachePolicyConfig:
        Name: DefaultPolicy
        Comment: Default cache policy of the Cloudblocks project S3 Content Distribution
        MinTTL: 86400
        DefaultTTL: 86400
        MaxTTL: 31536000
        ParametersInCacheKeyAndForwardedToOrigin:
          CookiesConfig: none
          QueryStringsConfig: none
          HeadersConfig: none


  # User pools 
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub "${ProjectName}-user-pool-${Environment}"
      AutoVerifiedAttributes:
        - email
      UsernameAttributes:
        - email
      Schema:
        - Name: email
          Required: true
          Mutable: false
          AttributeDataType: String
        - Name: name
          Required: true
          Mutable: true
          AttributeDataType: String

  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref UserPool
      ClientName: !Sub "${ProjectName}-user-pool-client-${Environment}"
      GenerateSecret: false

  StudentPoolGroup:
    Type: AWS::Cognito::UserPoolGroup
    Properties:
      GroupName: !Sub "${ProjectName}-students-group-${Environment}"
      UserPoolId: !Ref UserPool
      Description: User group for students. Students have access to enroll & see courses they are enrolled in.

  ProfessorPoolGroup:
    Type: AWS::Cognito::UserPoolGroup
    Properties:
      GroupName: !Sub "${ProjectName}-professors-group-${Environment}"
      UserPoolId: !Ref UserPool
      Description: User group for professors. Professors have access to create courses and manage their content.


  # API Gateway
  API:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors: "cloudblocks.gmorales.me"
      Auth:
        DefaultAuthorizer: CognitoAuthorizer
        Authorizers:
          CognitoAuthorizer:
            UserPoolArn: !GetAtt UserPool.Arn 


  # Functions
  GetUploadCourseSignedURL:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: courses/
      Handler: get_upload_signed_url.lambda_handler
      Runtime: python3.14
      Architectures:
        - x86_64
      Environment:
        Variables:
          CONTENT_BUCKET: !Ref ContentBucket
      Events:
        GetUploadCourseSignedURL:
          Type: Api
          Properties:
            RestApiId: !Ref API
            Path: /course
            Method: post
